print("this will make a funny story")
name = input("type a name: ")
place = input("type a place: ")
verb = input("type a verb: ")
noun = input("type a noun: ")
print(name, " went to "place, "where they" )