
print("This will calculate your budget")
income = int((input), "How much do you make a month?")
rent = int((input), "How much is your rent?")
utilities = int((input), "How much do you spend on utilities?")
groceries = int((input),"How much do you spend on groceries?")
transport = input("How much do you spend on transport?")
expenses = (rent, utilities, groceries, transport)
savings = (income*2)
total = (income + expenses)
prent = rent/income
putilities = (1*utilities/income)
pgroceries = (groceries/income)
ptransport = (transport/income)
print("your income is : $%.2%f")