name = input("What is your name?: ")
smlNum =  input("A number between 1 and 10: ")
lrgNum = input("A number between 100 and 1000: ")
food = input("What did you have for breakfast?: ")
color = input("What is your favorite color?: ")
school = input("What is the name of your school?: ")
year = input("What year is it?: ")
eye = input("What is your eye color: ")
age = input("What is your age?: ")
subject = input("What is your favorite subject in school?: ")
print(f"{name}, {smlNum}, {lrgNum}, {food}, {color}, {school}, {year}, {eye}, {age}, {subject}")